### ISSUE TITLE
Método WillHide não funciona em modo release

### ISSUE THREAD

**Issue by nildomacena** [IsaiasSantana/keyboard_utils#15]
O metódo WillHide não funciona em modo release. O método WillShow funciona normalmente. WillHide só funciona no modo debug.

**Comment by IsaiasSantana** [comment]
@nildomacena isso acontece no Android ou iOS?

**Comment by IsaiasSantana** [comment]
Pelo tempo sem resposta considero que isso não esteja acontecendo,  fechando.
