### ISSUE TITLE
not work on Android with flutter 1.17

### ISSUE THREAD

**Issue by adad184** [IsaiasSantana/keyboard_utils#17]
After upgrade flutter to version 1.17 today, i found keyboard change is not working properly with android project (on emulator).

with both `KeyboardListener` & `KeyboardAware` ( i tried both)

**Comment by nemoryoliver** [comment]
> After upgrade flutter to version 1.17 today, i found keyboard change is not working properly with android project (on emulator).
> 
> with both `KeyboardListener` & `KeyboardAware` ( i tried both)

Have you tried Beta? It's working on latest Flutter Beta for me. But I only tested a real device

**Comment by IsaiasSantana** [comment]
Hi @adad184. I haven't tested version 1.17 yet. I will check this problem.

**Comment by jpridavok** [comment]
The same problem here, did you have chance to check this problem?

**Comment by IsaiasSantana** [comment]
Hi @jpridavok. Not yet :(. In this weekend I will check this problem. I was vey busy another project.

**Comment by adad184** [comment]
any progress?

**Comment by IsaiasSantana** [comment]
@adad184  I have tested on flutter 1.17, it's working . May you show some log?

**Comment by IsaiasSantana** [comment]
@adad184 your project is pre 1.12 Android projects? may be useful to you https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by IsaiasSantana** [comment]
@adad184 Can you try 1.2.4 version?
