### ISSUE TITLE
Not working at all on emulator and partly on physical device - Android

### ISSUE THREAD

**Issue by omri1100** [IsaiasSantana/keyboard_utils#19]
Hi,

I used the package and it worked great!
Then I changed flutter version and it is working not good now.

```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.19041.264], locale en-IL)
    • Flutter version 1.17.1 at C:\Installations\flutter
    • Framework revision f7a6a7906b (5 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\omri1\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\omri1\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • SM G970F            • RF8M21HY5MZ   • android-arm64 • Android 10 (API 29)
    • AOSP on IA Emulator • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

I used it as regular. the event _onKeyboardListener is not called when the keyboard is closing on my Galaxy S10e and not called at all on my emulator.

Thank you!

**Comment by AramSemerjyan** [comment]
Same for Xiaomi Redmi 5

**Comment by IsaiasSantana** [comment]
@AramSemerjyan, @omri1100 Can you try 1.2.4 version?

**Comment by AramSemerjyan** [comment]
Thanks @IsaiasSantana for reply. I've tested it on iPhone 5s, iPad mini 5, Redmi 5 and also on iOS and Android simulators. Everything works perfectly. Thanks for a great package!

**Comment by AramSemerjyan** [comment]
Though:
I'm currently testing on Redmi 5 and keyboard size is wrong. This lib returns value of `234` and `flutter_keyboard_size` package returns `282`. Can it be related to keyboard additional view with tools?
![IMAGE 2020-06-30 19:24:24](https://user-images.githubusercontent.com/18259461/86144886-4ed57a80-bb07-11ea-80e4-ba87a0a36808.jpg)

**Comment by IsaiasSantana** [comment]
Hmm I don't know. I will check it. @AramSemerjyan .

**Comment by Farid566** [comment]
> Though @IsaiasSantana:
> I'm currently testing on Redmi 5 and keyboard size is wrong. This lib returns value of `234` and `flutter_keyboard_size` package returns `282`. Can it be related to keyboard additional view with tools?
> ![IMAGE 2020-06-30 19:24:24](https://user-images.githubusercontent.com/18259461/86144886-4ed57a80-bb07-11ea-80e4-ba87a0a36808.jpg)

Same problem :(
