### ISSUE TITLE
Android build error:Kotlin Gradle plugin version 1.3.0 and higher

### ISSUE THREAD

**Issue by BAGmail** [IsaiasSantana/keyboard_utils#3]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':keyboard_utils' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by wilfilho** [comment]
Hi @BAGmail 

We update kotlin version. Please, check latest version.
