### ISSUE TITLE
Fechar os issues resolvidos.

### ISSUE THREAD

**Issue by marcglasberg** [IsaiasSantana/keyboard_utils#36]
@IsaiasSantana e wilfilho, parabéns pelo plugin. Simples e funciona bem. 

@IsaiasSantana Seria interessante fechar (botão de "close") os issues que já foram resolvidos. Vi que a maioria dos 9 que estão abertos já estão resolvidos.

**Comment by IsaiasSantana** [comment]
Obrigado :) Irei fechar.
