### ISSUE TITLE
Issues with latest Flutter version

### ISSUE THREAD

**Issue by pazhut** [IsaiasSantana/keyboard_utils#39]
getting the following error:

'KeyboardListener' isn't a function. (Documentation)  Try correcting the name to match an existing function, or define a method or function named 'KeyboardListener'.
The name 'KeyboardListener' is defined in the libraries 'package:flutter/src/widgets/keyboard_listener.dart' and 'package:keyboard_utils/keyboard_listener.dart'. (Documentation)  Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

Flutter doctor:
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-CA)
    • Flutter version 2.6.0-5.2.pre at /Users/pazhutmann/Work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (17 hours ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/pazhutmann/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

**Comment by Drarox** [comment]
I did a pull request to fix this, it just need to be accepted : #38
