### ISSUE TITLE
Fail get the right height of Android device,  but normal on iOS

### ISSUE THREAD

**Issue by jims57** [IsaiasSantana/keyboard_utils#46]
### The following screen is about Android:
![image](https://user-images.githubusercontent.com/1920873/142797247-a669e6c3-75c2-44da-a529-75f0157e810c.png)

### The following screen is about iOS:
![image](https://user-images.githubusercontent.com/1920873/142797352-ca4d0601-ff2d-48de-9cb7-7156d53e82ab.png)

**Comment by jims57** [comment]
Fixed, it is not this package's problem. 
It is because the query method, `$('#toolbar').outerHeight();`, return different value between **Android** and **iOS**.

Thanks anyway.

**Comment by LostInDarkMath** [comment]
Hi @jims57 ,
I face the same issue. Can you share your solution here please?
