### ISSUE TITLE
Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by andyddd** [IsaiasSantana/keyboard_utils#7]
When run app on ios simulator with this plugin.  pod install says:
[!] Unable to determine Swift version for the following pods:
    - `keyboard_utils` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

flutter doctor:
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

**Comment by andyddd** [comment]
FYI, I create the app by objc template.

**Comment by danysz** [comment]
I still have the error on flutter 1.17 (beta)
